New styling and icons.
mt-support/tribe-ext-compact-view pull request #1
Opened 2020-12-10 20:43 UTC by Camwyn

Note quite done with styles, but can merge if needed to prevent conflicts.

2020-12-15 20:48 UTC, Camwyn commented
Marking this "ready for review since I did change a couple small php things. 
Can always create a DQA PR as needed.

2020-12-15 20:52 UTC, Camwyn commented on src/Tribe/Plugin.php
> +		//$this->container->register( PUE::class );
Not sure this should be in here? licensing?

2020-12-15 20:52 UTC, Camwyn commented on src/Tribe/Views/Summary_View.php
> +	 * @return \WP_Post
This was throwing param mismatch warnings

2020-12-15 20:52 UTC, Camwyn commented on src/views/v2/components/icons/summary.php
> + * View: Summary Icon
MCR is supposed to provide a tweaked version of this.

2020-12-15 20:52 UTC, Camwyn commented on src/views/v2/summary/event/date.php
> +		<?php elseif ( ! empty( $event->summary_view ) && $event->summary_view->start_date === $formatted_group_date ) : ?>
As discussed - this sometimes throws a warning, so we now check `empty()` before checking the value.

2021-01-06 17:10 UTC, borkweb requested changes
This looks pretty great! Just a couple of tweaks.

2021-01-06 17:10 UTC, borkweb commented on plugin.php
> +	$enabled_views[] = 'summary';
```suggestion
	if ( in_array( 'summary', $enabled_views ) ) {
		return;
	}
	
	$enabled_views[] = 'summary';
```

2021-01-06 17:10 UTC, borkweb commented on src/Tribe/Plugin.php
> +	protected function plugin_activated() {
Add a docblock here

2021-01-07 17:06 UTC, Camwyn commented on src/Tribe/Plugin.php
> +	protected function plugin_activated() {
Whups - removing this, it's unused.

2021-01-07 17:06 UTC, Camwyn commented on plugin.php
> +	$enabled_views[] = 'summary';
corrected (above marked line)

2021-01-08 15:56 UTC, borkweb approved these changes
:+1:

2021-01-08 15:57 UTC, merged